### ISSUE TITLE
Add meminput (member input) as option

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/nwmurl#1]
Fix hard-coded input here: https://github.com/CIROH-UA/nwmurl/blob/afd5a8e03663c6e01545ab2dd0f2808442370b25/nwmurl/urlgennwm.py#L446

Also needs some documentation to explain what the meminput is (it is the ensemble member designation)

Also could include some validation/checking -- there is no ensemble (and therefore no ensemble members) for short_term, analysis_assim, nor forcing.

**Comment by sepehrkrz** [comment]
Done #4
