### ISSUE TITLE
Remove stray notebook checkpoint folder and files

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/nwmurl#30]
There is an IPython notebook checkpoint folder in the directory tree -- probably not intentional.
If it is not needed, we should delete this and the checkpoint folder that contains it. 
https://github.com/CIROH-UA/nwmurl/blob/main/nwmurl/.ipynb_checkpoints/urlgennwm-checkpoint.py

**Comment by sepehrkrz** [comment]
It was not needed and it is deleted now. Thanks for pointing that out.
