### ISSUE TITLE
Limit zero padding for analysis_assim

### ISSUE THREAD

**Issue by sepehrkrz** [CIROH-UA/nwmurl#36]
The Analysis and Assim urls from this tool have too many zeros in the name -- the ana names are `tm00`, `tm01`, etc. The forecast names are `f001`, `f002`, `f003`, etc. 

The name generator was built (apparently) with the 3-digit padding for the forecast names and produces output like, `tm000` and `tm001` for the AnA urls. 
(Compare outputs here for context: 
https://nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/v3.0/)

**Comment by jameshalgren** [comment]
The problem is essentially this line: 
https://github.com/CIROH-UA/nwmurl/blob/d2b9676af8cdb706349b0afe2d8f54adfc380c7a/nwmurl/urlgennwm.py#L64C96-L64C108

The string code `{fcst_hour:03d}` produces a three-zero pad -- but for analysis_assim outputs, that needs to be just a two zero pad.
